### PR TITLE
Modification for FCS3.2 Compatibility

### PR DESCRIPTION
**Pull request by Newlyn01**
This pull request adresses the need for compatibility with FCS3.2 data.
The following changes have been made:
- in R/IO.R line 17: Added "FCS3.2" as possible version
- in R/IO.R lines 671-672: Added "FCS3.2" as possible version + updated the stopmessage

### CODE REVIEW

**Comment by gfinak** [comment]
Please do not check in `.o` object files.

**Comment by mikejiang** [comment]
The actual FCS3.2 support is yet to be implemented

**Comment by SofieVG** [comment]
While the implementation of additional support for FCS3.2 would be much appreciated, we found it already useful to have this in-between fix just so we can read in the fcs files and access the numeric values in R, which otherwise is not possible at all. As we thought this might be helpful for others as well, we thought a pull request might be appropriate. Maybe we can still add a warning for FCS3.2 stating it is not fully supported yet, rather than having it stop on the error completely?

**Comment by Newlyn01** [comment]
I have reverted the commit where .o files got pushed. I have now also added a warning message saying that FCS3.2 is not fully supported yet by the flowCore package. This warning will only be returned when an FCS3.2 file is read.

**Comment by gfinak** [comment]
@mikejiang I'm okay with this change, feel free to merge.

**Review by mikejiang — APPROVED** [review]

**Pull request merged**
